---
- name: cron module
  hosts: controllers
  tasks:
   - name: docker save
     ansible.builtin.cron:
      name: "docker save"
      state: present
      minute: "0"
      hour: "22"
      day: "*"
      month: "*"
      weekday: "1"
      job: "0 20 * * 2 /opt/scripts/dockersave.sh >>/opt/scripts/dockersaveoutput.log 2>&1"
